fixtures:
  forge_modules:
    apache:
      repo: 'puppetlabs/apache'
      ref: '1.1.1'
    concat:
      repo: 'puppetlabs/concat'
      ref: '1.0.0'
    git:
      repo: 'puppetlabs/git'
      ref: '0.3.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.5.1'
    vcsrepo:
      repo: 'puppetlabs/vcsrepo'
      ref: '1.2.0'
  symlinks:
    kibana3: "#{source_dir}"
