rvm: 1.8.7
notifications:
  email:
    - alejandro@ideasftw.com
env:
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=2.7.25
